= ProGramm - Exploration tool for Chomsky type 2 grammars.
:gpp: g++
:cpp: C++

== Building

=== Windows

* Install a recent version of Visual Studio 2019 or later (hereafter called VS).
* After starting VS, select "Clone a repository".
* Enter `https://github.com/sewpalu/ProGramm.git` as the repository location.
* Wait for the repository to be cloned and the CMake cache to be built.
  The output window (set to "CMake" output) should show the line `CMake generation finished.`
* Select "GUI" as the startup item in the green play-button-widget at the top.
* Click the play-button-widget to build and run.

=== Linux

[source,sh]
----
git clone --recurse-submodules https://github.com/sewpalu/ProGramm.git
cd ProGramm

# Build and run
make run
# Or: Build only
make build
----

NOTE: {gpp}-10 or later is required to build the application. On Ubuntu 20.04 it can be installed using `sudo apt install {gpp}-10`. If the appropriate compiler isn't automatically used (i.e. there are compile errors) prepend `CXX=<specific {gpp} executable>` to the make calls. For example: `make clean; CXX={gpp}-10 make run`.

NOTE: It is necessary that git, CMake, a {cpp} compiler and the development library for GTK+ 3 are installed to build the application. On Ubuntu, for example, this command may be executed in order to install them: `sudo apt update && sudo apt install -y git cmake {gpp}-10 libgtk-3-dev`.

== Prebuilt binaries

Prebuilt binaries are available via the releases on this https://github.com/sewpalu/ProGramm[GitHub] repository. Simply unzip them and start the GUI via the `pro_gramm_gui.bat` (Windows) or `pro_gramm_gui.sh` (Linux) script, or use the CLI directly. As of now, the working directory of the application has to be the unzipped directory.

