= ProGramm - Exploration tool for Chomsky type 2 grammars.

== Building

=== Windows

* Install a recent version of Visual Studio 2019 or later (hereafter called VS).
* After starting VS, select "Clone a repository".
* Enter `https://github.com/sewpalu/ProGramm.git` as the repository location.
* Wait for the repository to be cloned and the CMake cache to be built.
  The output window (set to "CMake" output) should show the line `CMake generation finished.`
* Select "GUI" as the startup item in the green play-button-widget at the top.
* Click the play-button-widget to build and run.

=== Linux

[source,sh]
----
git clone --recurse-submodules https://github.com/sewpalu/ProGramm.git
cd ProGramm

# Build and run
make run
# Or: Build only
make build
----

NOTE: gcc-10 (or later) or clang-11 (or later) are required to build the application. On Ubuntu 20.04 these can be installed using `sudo apt install clang-11`, for example. If the appropriate compiler isn't automatically used (i.e. there are compile errors) prepend `CXX=<specific gcc or clang executable>` to the make calls. For example: `CXX=clang-11 make run` 

=== Mac OS

TODO

== Prebuilt binaries

TODO

